### ISSUE TITLE
org2nikola-export-subtree adds subtree headline as a heading

### ISSUE THREAD

**Issue by joonro** [masayuko/ox-nikola#1]
Hi,

I'm using `ox-nikola` Version: 20150901.1507 from melpa, and I found that whenever I run `(org2nikola-export-subtree)`, it adds the headline of the subtree as a heading. For example, if I have 

``` org
* post title
Text
** header 1
Text
```

the resulting blog post (basically) becomes

``` rst

=========
post title
=========

post title
=======

Text

header 1
----------

Text
```

instead of

``` rst

=========
post title
=========

Text

header 1
=======

Text
```

**Comment by msnoigrs** [comment]
It cannot be reproduced and I have never been used org2nikola. It seems that you should check your configuration. 
I look org2nikola a little, that doesn't call ox-nikola (org-nikola-export-to-rst).

**Comment by joonro** [comment]
I should have reported this to org2nikola - I was mistaken. I'm sorry!
