### ISSUE TITLE
newline in between = and = should be removed in export

### ISSUE THREAD

**Issue by joonro** [masayuko/ox-nikola#2]
Hi,

I have the following in my org file:

``` org
2. In =Document= > =Settings= > =Output=, check =Synchronize with
   output=. (checked by default)
```

The ox-nikola exports it like the following:

``` rst
2. In ``Document`` > ``Settings`` > ``Output``, check ``Synchronize with
      output``. (checked by default)
```

Which causes the following error:

``` python
System Message: WARNING/2 (<string>, line 9); backlink

Inline literal start-string without end-string.
```

It seems the newline between `=Synchronize with` and `output=` should be removed before exporting.

Thank you!

**Comment by msnoigrs** [comment]
I have fixed this issue at https://github.com/masayuko/ox-rst/commit/9279bdef9b07b4936b7f2674a1632aadfc698681
Please update ox-rst.el and check it.

**Comment by joonro** [comment]
Thank you! May I ask you when would it be available in melpa?

**Comment by msnoigrs** [comment]
It can be available now. melpa updates is auto and I don't know the schedule for updates.
